chat vc UI
FIT-I/FIT-I-Android pull request #17
Opened 2023-01-12 15:39 UTC by gurino

Chat VC 채팅방 목록 UI 완성했습니다.

2023-01-13 01:38 UTC, HI-JIN2 commented
goolge-service.json 파일은 삭제 하시고 gitignore에 올려주세요! 외부에 공개되면 안되는 파일이라서 깃에 올리면 안됩니다...! 슬랙을 통해 파일 공유 해주시면 됩니다.

2023-01-13 01:45 UTC, HI-JIN2 commented
이런 식으로 drawble 파일 정리해주시면 감사하겠습니다!

- 아이콘의 경우 ic_~~
- 이미지의 경우 img_~~
- 이미지 버튼의 경우 imb_~~

![image](https://user-images.githubusercontent.com/94737714/212217891-6ca637b6-70ae-440d-9b83-c328d25b8345.png)

2023-01-13 01:50 UTC, HI-JIN2 requested changes

2023-01-13 01:50 UTC, HI-JIN2 commented on app/src/main/java/com/example/fit_i/ChatFragment.kt
> +        //사진은 어떻게하지??
사진 데이터는 glide를 사용해서 작업하는 걸로 알고 있습니다!

2023-01-13 01:52 UTC, HI-JIN2 commented on app/src/main/java/com/example/fit_i/ChatFragment.kt
> +        //사진은 어떻게하지??
사진 데이터는 glide를 사용해서 작업하는 걸로 알고 있습니다!

2023-01-13 08:22 UTC, gurino commented on app/src/main/java/com/example/fit_i/ChatFragment.kt
> +        //사진은 어떻게하지??
감사합니다!!

2023-01-15 08:29 UTC, HI-JIN2 commented on app/src/main/res/menu/menu.xml
> +        android:icon="@drawable/ic_house"
ic 변경에 대한 커밋을 되돌릴 수 있을까요? menu가 selector를 이용해서 클릭시 색상을 바뀌게 해놔서 파일명을 변경하시면 안됩니다ㅠㅜㅠ

2023-01-15 10:45 UTC, merged